version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000" # FastAPI (main.py)
      - "5000:5000" # Flask (auth.py)
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - STEAM_API_KEY=${STEAM_API_KEY}
      - ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    stdin_open: true
    tty: true

  db:
    image: postgres:15  # Use the latest stable PostgreSQL version
    restart: always
    environment:
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER: steamrail_admin
      POSTGRES_PASSWORD: steamrail_p@55w0rd!
      POSTGRES_DB: steamrail
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
